version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: "3.9"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/raptgen
    command: ["conda", "run", "-n", "raptgen", "python", "app.py"]
    depends_on:
      - jupyter

  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - .:/home/work
    ports:
      - "8888:8888"